site_name: 无忌
site_url: https://Hujiko02.github.io
site_author: 无忌
site_description: 无忌的个人网站

theme:
  name: material
  # 语言设置为中文
  language: zh
  # 配色方案（可切换明暗模式）
  palette:
    - scheme: default
      primary: indigo
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: 浅色模式
    - scheme: slate
      primary: indigo
      accent: amber
      toggle:
        icon: material/weather-night
        name: 深色模式

  features:
    - navigation.instant # 即时页面加载
    - navigation.tabs # 顶部标签页导航
    - navigation.sections # 侧边栏分组显示
    - toc.integrate # 集成目录
    - search.suggest # 搜索建议
    - search.highlight # 搜索高亮

nav:
  - 首页: index.md
  - 摘录:
    - 世界尽头与冷酷仙境: extract/End of the World and Hard-Boiled Wonderland.md
  - 关于我: about.md

extra:
  social: 
    - name: 我的GitHub
      icon: fontawesome/brands/github
      link: https://github.com/Hujiko02
    - name: 我的Bilibili
      icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/2058282898
   
# 扩展功能
plugins:
  - search # 启用搜索插件（Material主题自带）

